### ISSUE TITLE
Symbols for Events

### ISSUE THREAD

**Issue by weidingergerald** [AnotherCodeArtist/medien-transparenz.at#106]

**Comment by weidingergerald** [comment]
YES: 
http://stackoverflow.com/questions/18416749/adding-fontawesome-icons-to-a-d3-graph

**Comment by relative-progressio** [comment]
- The font family is called 'Glyphicons Halflings'. Add the attribute to the text node.
- needed for events to show a symbol for details and to show if event is predictable or not.
