### ISSUE TITLE
Run/Build failure (mean.io & Angular 1.6)

### ISSUE THREAD

**Issue by relative-progressio** [AnotherCodeArtist/medien-transparenz.at#144]
Running MTA from scratch (after fresh `npm install`) fails, since the newest AngularJS version (required by mean.io’s` bower.json`) does not include the `$http`-callback methods: `success()/error() `as pointed out in the [changelog](https://github.com/angular/angular.js/blob/master/CHANGELOG.md).  The methods have been deprecated and now removed, as the [documentation](https://code.angularjs.org/1.5.9/docs/api/ng/service/$http) shows. 

A quick search for the `success()` method in the transparency-package showed that the method is used in the `checkLoggedIn` function. This is something to refactor.

More importantly, the mean.io package (at least in the used version) seams not prepared for that breaking change. For example, the mean-users page uses `success()`. (see: [this issue](https://github.com/linnovate/meanio-users/issues/6)) Possibly more mean-packages are affected. 

It may be an option to downgrade the (angular-related?)-packages in the mean.io's `bower.json`, as long as this issue is not resolved.

**Comment by AnotherCodeArtist** [comment]
Downgrading to working version seems to be the best Option.
