### ISSUE TITLE
Different Semantics of Filter and Search Terms

### ISSUE THREAD

**Issue by AnotherCodeArtist** [AnotherCodeArtist/medien-transparenz.at#15]
The filer term "Österreich" typically produces to many entries as well. In cases like this, there should probably appear a list with all organizations and media that matches the term, so the the user can drill down more easily.
This could also be accompanied with some animated help, explaining the different options
Also the combinations of filters and the selection of an organization or media seems to be confusing

**Comment by relative-progressio** [comment]
Since there is no filter anylonger, this story can be closed.
