### ISSUE TITLE
Adding events

### ISSUE THREAD

**Issue by AnotherCodeArtist** [AnotherCodeArtist/medien-transparenz.at#28]
It should be possible to add events (e.g. general election) with a date. These events are later shown on a time line. Besides a name and a date events should also have regional information and/or information about the administrative level (national, provincial, district, municipal, ...) respectively. This would allow to show these events on the time line whenever they are relevant (see [issue #18](https://github.com/AnotherCodeArtist/medien-transparenz.at/issues/18)).
Alternatively all events could be rendered with an option to hide them selectively.

**Comment by weidingergerald** [comment]
Creating, editing and deleting of events is now possible with the new role 'editor' in the editor branch

**Comment by weidingergerald** [comment]
event management should be possible for every user with role 'editor'

**Comment by weidingergerald** [comment]
event icon should be same color like the other icons

**Comment by weidingergerald** [comment]
admins can now manage events. check on role 'editor' does not work

**Comment by weidingergerald** [comment]
users with the circle 'can manage events' and administrators may now manage events
