### ISSUE TITLE
Aggregate Organizations/Media to Groups

### ISSUE THREAD

**Issue by AnotherCodeArtist** [AnotherCodeArtist/medien-transparenz.at#29]
- It should be possible to combine different organizations ("Stadt Wien", "Wiener Linien", ...) to groups. As a result such a group should be rendered as if it was single organization. The same thing should also work for media
- Every single user (which does not require registration or login) should be able to create such groups (they could be store in the browser local storage so that are at least partially persistent).
- If a member (=registered user) creates such groups, it should be possible to share them with other members or the general public (might require some staging mechanism).
- Generally these groups should be available on all pages

**Comment by relative-progressio** [comment]
Related to #62, #63

**Comment by relative-progressio** [comment]
Also consists of #86, #89
