### ISSUE TITLE
Aggregate Data on Regional/Administrative Level

### ISSUE THREAD

**Issue by AnotherCodeArtist** [AnotherCodeArtist/medien-transparenz.at#33]
It should be possible to automatically groups all public agencies/governmental entities within a province in order to make provinces more comparable (e.g. Vienna = City + Province)

**Comment by relative-progressio** [comment]
We should ask the  Austrian Court of Audit to provide, if an organisation belongs to federal or provincial government. 

Additionally , we should check if there is some OGD  available, to automate this.

**Comment by weidingergerald** [comment]
Since there is no support by the Austrian Court of Audit this feature has to be discarded
