### ISSUE TITLE
Providing a timeline

### ISSUE THREAD

**Issue by AnotherCodeArtist** [AnotherCodeArtist/medien-transparenz.at#36]
In order to make changes of transfers over time more obvious a timeline should be presented.
This timeline could become visible once a user clicks on a flow in the sankey diagram.
It should be possible to add several legal entities (organizations) and media to this view. 
When comparing time series there should also be a stacked and a non-stacked view.
The time series should be shown as a continuous flow of quarters or as an overlay of years. This is important since there are seasonal changes over quarters. Thus, showing the changes in comparison to the same quarter a year ago would be more meaningful. 

Maybe this could be a nice basis: http://bl.ocks.org/mbostock/1256572

**Comment by weidingergerald** [comment]
An timeline is implemented as flow details for one organsiation to one media enterprise.

One timeline contains the amount of money per quarter.

The other timeline shows an annual comparison where it is shown how much money is spent each year quarterwise.

**Comment by weidingergerald** [comment]
change timeline for flow details to histograms

**Comment by weidingergerald** [comment]
add user support for selecting and deselecting years in annual comparison
