### ISSUE TITLE
Sort bars in overview from most recent to oldest

### ISSUE THREAD

**Issue by AnotherCodeArtist** [AnotherCodeArtist/medien-transparenz.at#8]
Re-order the bars in the overview diagram so that the most recent one is left instead of right. Maybe the color scheme can also be used to contribute to the readability of the charts

**Comment by AnotherCodeArtist** [comment]
That's actually the way it is now!?!

**Comment by relative-progressio** [comment]
The most recent one should be right.

**Comment by AnotherCodeArtist** [comment]
Implemented in branch fix-order-of-bars-#8
