### ISSUE TITLE
Refinement: 3D map

### ISSUE THREAD

**Issue by relative-progressio** [AnotherCodeArtist/medien-transparenz.at#82]
Issue related to #57:
- transperent color is a little bit distracting
- overlapping of federal states
- detection of federal states strange (sometimes displaced)
- borders overlapping (Styira, Lower Austria, Burgenland)
- menu item should be renamed to "Über uns" (just shorter)

**Comment by AnotherCodeArtist** [comment]
![astria3dchart](https://cloud.githubusercontent.com/assets/6880844/17286802/049b22be-57cc-11e6-8057-5634d04ee4d6.png)
Here's a screenshot showing the problems. Upper-Austria is only detected, when the point is at the position where the popup is rendered.
