### ISSUE TITLE
Refinement: Flow page

### ISSUE THREAD

**Issue by relative-progressio** [AnotherCodeArtist/medien-transparenz.at#83]
-  Save state of selected media and organisation
- Optimisation of selecting media or organisation (if there is more than 100 entries: drop downs do not make any sense.) Maybe one solution would be to store the media list in session store, to cache it. Therefore, bringing up an activity indicator when downloading the list first time.
- If no media or organisation is selected, there should be some default selection (e.g.: Stadt Wien as the biggest spender (#14))
- "Other organisations" and "other media" should be translated within the datatable too.
- Check setting on mobile devices (use of rows) to make sure that the diagramm has as much space as possible. Maybe the selections should be moved to the top of the page.
- Placeholder in select-boxes needs to be translated

**Comment by weidingergerald** [comment]
is implemented in branch refine_showflow#83 (placeholder is not translated; labels are shown)
